# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\x12\x05stash\"1\n\x06Player\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\x12\r\n\x05\x63\x61rds\x18\x03 \x03(\r\"\xb5\x01\n\tGameState\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x14\n\x0cplayer_count\x18\x02 \x01(\r\x12\x12\n\ncard_count\x18\x03 \x01(\r\x12\n\n\x02id\x18\x04 \x01(\t\x12\x10\n\x08\x63reation\x18\x05 \x01(\t\x12\x0f\n\x07\x63urrent\x18\x06 \x01(\r\x12\x11\n\tclockwise\x18\x07 \x01(\x08\x12\x0b\n\x03ref\x18\x08 \x01(\r\x12\x1e\n\x07players\x18\t \x03(\x0b\x32\r.stash.Player\"8\n\x08Opponent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ncard_count\x18\x02 \x01(\r\x12\n\n\x02id\x18\x03 \x01(\r\"\xca\x01\n\x0bPlayerState\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x14\n\x0cplayer_count\x18\x02 \x01(\r\x12\x12\n\ncard_count\x18\x03 \x01(\r\x12\n\n\x02id\x18\x04 \x01(\t\x12\x11\n\tplayer_id\x18\x05 \x01(\r\x12\x10\n\x08\x63reation\x18\x06 \x01(\t\x12\x0f\n\x07\x63urrent\x18\x07 \x01(\r\x12\x0b\n\x03ref\x18\x08 \x01(\r\x12\r\n\x05\x63\x61rds\x18\t \x03(\r\x12\"\n\topponents\x18\n \x03(\x0b\x32\x0f.stash.Opponent')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYER']._serialized_start=22
  _globals['_PLAYER']._serialized_end=71
  _globals['_GAMESTATE']._serialized_start=74
  _globals['_GAMESTATE']._serialized_end=255
  _globals['_OPPONENT']._serialized_start=257
  _globals['_OPPONENT']._serialized_end=313
  _globals['_PLAYERSTATE']._serialized_start=316
  _globals['_PLAYERSTATE']._serialized_end=518
# @@protoc_insertion_point(module_scope)
